import { StyleSheet } from "react-native";

export const confirmationStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.9)",
    padding: 16,
  },
  confirmationCard: {
    width: "90%",
    maxWidth: 400,
    backgroundColor: "#111",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: "#0f0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  iconContainer: {
    marginBottom: 24,
    shadowColor: "#0f0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    backgroundColor: "transparent",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#0f0",
    marginBottom: 24,
  },
  detailsContainer: {
    width: "100%",
    marginBottom: 24,
    backgroundColor: "transparent",
  },
  detailsLabel: {
    fontSize: 14,
    color: "#888",
    marginBottom: 4,
  },
  detailsValue: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 16,
  },
  message: {
    fontSize: 14,
    color: "#ccc",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 20,
  },
  primaryButton: {
    backgroundColor: "#0f0",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 10,
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 12,
    shadowColor: "#0f0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
  },
  primaryButtonText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "bold",
  },
  secondaryButton: {
    paddingVertical: 12,
    width: "100%",
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#0f0",
    fontSize: 14,
  },
  buttonIcon: {
    marginRight: 8,
  },
});
